# Link the C runtime into the executables so onset.exe runs on a Windows PC without the
# Visual C++ Redistributable installed.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
